## **Machine Learning Logisitic Regression  Challenge on Income Data Set**
Welcome to the machine learning challnege, in this scenario, you will be exploring logistic regression on income dataset

**Note** -
- Write the solution in this notebook by adding cells and follow the given instructions below. (Add additional notebook for coding if necessary)


## Provided Dataset and Instructions


 - The dataset provided here is income.csv has 43957 records with a target attribute as **income_>50K** containing values **1** and **0**.
 
 
 - Use this dataset to build the model by splitting the data into train and test split. (Here keep 80% of data as train dataset and remaining as test dataset)
 
 
- The final score evaluation is based on Accuracy Score, Macro - F1 Score and Area Under the ROC Curve Score (ROC - AUC Score),Sensitivity ,Specificity and confusion matric on the test dataset.


- **Hint** - Here try treating the null values and tuning the parameters of the model for better performance of the model

### Submission Details

- Write the code to build the model and predicts the `income_>50K` (0 or 1) for the records in test dataset.



- Once the predictions are ready kindly calculate the metrics accuracy, macro-f1 score, roc-auc score , sensitivity, specificity and confusion matrix and save it in the variables **income_acc**,**income_f1_macro** , **income_roc** , **income_sensitivity** ,**income_specificity** and **income_confusion**. 




**Note**

- Here, run the first two cells to import the necessary packages and to download the datasets, and final two cells to save the results in the directory and to evaluate the results. 



- Here , this is the categorical codes for the target variable `income_>50K` -

 

- no - 0,

- yes - 1



- Additional packages can be installed in the notebook using the command: 

		 !pip3 install --user package_name

## Run the below cell to import the necessary packages required for the challenge

In [1]:
#Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn

## Run the below cell to download the dataset

In [2]:
!wget hrcdn.net/s3_pub/istreet-assets/jPlUtUXGWJSIuuj0QIpMNg/income.csv

--2021-09-15 14:12:55--  http://hrcdn.net/s3_pub/istreet-assets/jPlUtUXGWJSIuuj0QIpMNg/income.csv
Resolving hrcdn.net (hrcdn.net)... 2600:140f:5::6011:c252, 2600:140f:5::6011:c273, 23.200.218.114, ...
Connecting to hrcdn.net (hrcdn.net)|2600:140f:5::6011:c252|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://hrcdn.net/s3_pub/istreet-assets/jPlUtUXGWJSIuuj0QIpMNg/income.csv [following]
--2021-09-15 14:12:55--  https://hrcdn.net/s3_pub/istreet-assets/jPlUtUXGWJSIuuj0QIpMNg/income.csv
Connecting to hrcdn.net (hrcdn.net)|2600:140f:5::6011:c252|:443... connected.
ERROR: cannot verify hrcdn.net's certificate, issued by 'CN=DigiCert SHA2 Secure Server CA,O=DigiCert Inc,C=US':
  Unable to locally verify the issuer's authority.
To connect to hrcdn.net insecurely, use `--no-check-certificate'.


### Follow the below steps for building the solution

  - Read the dataset and have a look at the attributes of the dataset.
  
  
  - Look for null values in the dataset and treat those null values with appropriate techniques.
  
  
  - Convert the categorical columns to numerical column by label encoding those columns.
  
  
  - Select the values for dependent and independent variables and split the dataset into train and test dataset. (Select 80% of data for training and remaining data as test dataset).
  
  
  - Fit the logisitc regression model by fine tuning the hyperparameters of the model.
  
  
  - Evaluate the results by calculating the above mentioned metrics and save it in the apporpiate variables as mentioned in the instructions.
  
  
   - Run the final two cells to save and validate the results.

In [3]:
#Write your code here and add more cells for coding


df = pd.read_csv('income.csv')

df.shape





(43957, 15)

In [4]:
df.isnull().sum()

age                   0
workclass          2498
fnlwgt                0
education             0
educational-num       0
marital-status        0
occupation         2506
relationship          0
race                  0
gender                0
capital-gain          0
capital-loss          0
hours-per-week        0
native-country      763
income_>50K           0
dtype: int64

In [5]:
df=df.dropna()

In [6]:
y = df.values[:,14]
df = df.drop('income_>50K', axis=1)
y

array([1, 0, 1, ..., 0, 0, 0], dtype=object)

In [7]:
df1 =df,
def age_grp(x):
    if (x<=25):
        return('Young')
    elif(x>25 and x<=60): 
        return('Middle Age')
    else:
        return('Senior')

def workclass(x):
    if (x == 'Private'):
        return('Private')
    else:
        return('Others')
    
def edu_grp(x):
    if (x=='12th' or x=='11th' or x=='10th' or x=='12th' or x=='1st-4th' or x=='5th-6th' or x=='7th-8th' or x=='9th' or x=='Preschool'): 
        return('LessEducated')
    elif(x== 'Doctorate' or x == 'Prof-school' or x == 'Masters'): 
        return('HighlyEducated')
    else:
        return('Educated')

In [8]:
def preprocessing(df):
    df1=df
    df1['Age_Group'] = df['age'].apply(lambda x:age_grp(x))
    df1['workclass1'] = df1['workclass'].apply(lambda x:workclass(x))
    df['education_category'] = df['education'].apply(lambda x:edu_grp(x))
    df1= pd.get_dummies (df1, columns =['Age_Group'], drop_first=True)
    df1 = pd.get_dummies (df1, columns =['gender'], drop_first=True)
    df1 = pd.get_dummies(df1, columns =['workclass1'], drop_first=True)
    df1 = pd.get_dummies(df1, columns =['education_category'], drop_first=True)
    df1 = pd.get_dummies(df1, columns=['occupation'], drop_first=True)
    df['education_category'] = df['education'].apply(lambda x:edu_grp(x))
    #df1['workclass].value_counts 0,
    df1= pd.get_dummies (df1, columns =['marital-status'], drop_first=True)
    df1= pd.get_dummies (df1, columns =['race'], drop_first=True)
    df1=df1.drop(['relationship', 'native-country', 'age', 'fnlwgt', 'workclass', 'education','capital-gain','capital-loss'], axis=1)
    print(df1.columns)
    print(df1.head())
    x=df1.values[:,:]
    return x

In [9]:
x=preprocessing(df)
print(x.shape) 
y = y.reshape(-1, 1)
y=y.astype('int') 



Index(['educational-num', 'hours-per-week', 'Age_Group_Senior',
       'Age_Group_Young', 'gender_Male', 'workclass1_Private',
       'education_category_HighlyEducated', 'education_category_LessEducated',
       'occupation_Armed-Forces', 'occupation_Craft-repair',
       'occupation_Exec-managerial', 'occupation_Farming-fishing',
       'occupation_Handlers-cleaners', 'occupation_Machine-op-inspct',
       'occupation_Other-service', 'occupation_Priv-house-serv',
       'occupation_Prof-specialty', 'occupation_Protective-serv',
       'occupation_Sales', 'occupation_Tech-support',
       'occupation_Transport-moving', 'marital-status_Married-AF-spouse',
       'marital-status_Married-civ-spouse',
       'marital-status_Married-spouse-absent', 'marital-status_Never-married',
       'marital-status_Separated', 'marital-status_Widowed',
       'race_Asian-Pac-Islander', 'race_Black', 'race_Other', 'race_White'],
      dtype='object')
   educational-num  hours-per-week  Age_Group_Senior 

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(x, y, test_size=0.20, random_state=42)
print(X_train)

[[ 7 35  0 ...  0  0  1]
 [ 6 15  0 ...  0  0  1]
 [13 40  0 ...  0  0  1]
 ...
 [12 40  0 ...  0  0  1]
 [10 60  0 ...  0  0  1]
 [ 9 38  0 ...  0  0  1]]


In [12]:
from sklearn.linear_model import LogisticRegression
log_reg = LogisticRegression(solver='liblinear', C=1,penalty='l1',class_weight='balanced')
log_reg.fit(X_train,y_train)


C:\Users\Sudip\Anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression(C=1, class_weight='balanced', penalty='l1',
                   solver='liblinear')

In [120]:
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.metrics import roc_curve, precision_recall_curve, auc, make_scorer, recall_score, accuracy_score, precision_score, confusion_matrix

model = LogisticRegression()
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l1', 'l2', 'elasticnet' , 'none']
c_values = [100, 10, 5,1.0, 0.1, 0.01]
scorers = {
    'precision_score': make_scorer(precision_score),
    'recall_score': make_scorer(recall_score),
    'accuracy_score': make_scorer(accuracy_score)
}
scoring = {
#    'accuracy': make_scorer(accuracy_score),
#    'sensitivity': make_scorer(recall_score),
    'specificity': make_scorer(recall_score,pos_label=0)
}
# define grid search
refit_score='precision_score'
grid = dict(solver=solvers,penalty=penalty,C=c_values)
skf = StratifiedKFold(n_splits=10)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=skf, scoring=scoring,refit=False,
                          return_train_score=False)
grid_result = grid_search.fit(X_train,y_train)
# summarize results
print('Best params for {}'.format(refit_score))
#print(grid_search.best_params_)

print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))

Best params for precision_score


C:\Users\Sudip\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.91759184 0.91763265 0.91444898 0.91763265
        nan        nan        nan 0.91763265 0.91506122        nan
        nan        nan 0.9175102  0.91763265 0.91681633 0.91759184
        nan        nan        nan 0.91763265 0.91506122        nan
        nan        nan 0.91767347 0.91763265 0.91669388 0.91759184
        nan        nan        nan 0.91763265 0.91506122        nan
        nan        nan 0.91771429 0.91791837 0.91689796 0.91812245
        nan        nan        nan 0.91763265 0.91506122        nan
        nan        nan 0.91934694 0.91918367 0.9184898  0.91930612
        nan        nan        nan 0.91763265 0.91506122        nan
        nan        nan 0.93273469 0.92918367 0.92946939 0.92787755
        nan        nan        nan 0.91763265 0.91506122        nan]
  warnings.warn(


AttributeError: 'GridSearchCV' object has no attribute 'best_score_'

In [109]:
scorers

{'precision_score': make_scorer(precision_score),
 'recall_score': make_scorer(recall_score),
 'accuracy_score': make_scorer(accuracy_score)}

In [13]:
y_predict = log_reg.predict(X_test)

In [14]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score

In [20]:
income_acc = accuracy_score(y_test,y_predict)
income_f1_macro = f1_score(y_test,y_predict,average='macro')
income_roc=roc_auc_score(y_test,y_predict)
income_confusion=confusion_matrix(y_test,y_predict)
total1=sum(sum(income_confusion))
income_sensitivity=income_confusion[0,0]/(income_confusion[0,0]+income_confusion[0,1])
income_specificity=income_confusion[1,1]/(income_confusion[1,0]+income_confusion[1,1])



In [21]:
print('Accuracy:',income_acc)
print('F1 Macro:',income_f1_macro)
print('ROC:',income_roc)
print('Confusion Matrix:',income_confusion)
print('Sensitivity:',income_sensitivity)
print('Specificity:',income_specificity)
income_confusion[0]

Accuracy: 0.7744905475079794
F1 Macro: 0.7389689668050075
ROC: 0.7902845271949671
Confusion Matrix: [[4657 1478]
 [ 359 1652]]
Sensitivity: 0.7590872045639772
Specificity: 0.8214818498259573


array([4657, 1478], dtype=int64)

## Run the below cell to save your results

In [17]:
import pickle

with open("Confusion_Matrix.txt", "wb") as fp:   #Pickling
    pickle.dump(income_confusion, fp)
    
with open("Accuracy.txt", "wb") as fp:   #Pickling
    pickle.dump(income_acc, fp)
    
    
with open("F1-Score-Macro.txt", "wb") as fp:   #Pickling
    pickle.dump(income_f1_macro, fp)
    
    
with open("ROC-Score.txt", "wb") as fp:   #Pickling
    pickle.dump(income_roc, fp)
    
    
with open("Sensitivity.txt", "wb") as fp:   #Pickling
    pickle.dump(income_sensitivity, fp)
    
    
with open("Specificity.txt", "wb") as fp:   #Pickling
    pickle.dump(income_specificity, fp)

## Run the below cell to validate the results

In [19]:
python test.py

SyntaxError: invalid syntax (<ipython-input-19-83c175a3a2f1>, line 1)